### ISSUE TITLE
建议新增填入视频链接时自动填充视频名称的功能。

### ISSUE THREAD

**Issue by AngusLkc** [caorushizi/mediago#127]
另外这个软件不管当前运行的是不是最新版本，都会强制从服务器上下载最新版本安装到本地是为了有需要的时候分发私货吗？

**Comment by caorushizi** [comment]
代码是开源的，并且所有的 release 都是 verified。如果有疑问你可以看下源代码。标题的建议后续会添加。

**Comment by caorushizi** [comment]
默认代入标题，或者标题可不填。B 站代入默认标题
