### ISSUE TITLE
请求发布便携版本！

### ISSUE THREAD

**Issue by ScienceZone** [caorushizi/mediago#180]
如题所述，希望大佬发布便携版本！正如很多人说的一样，软件的作用是使用而不是安装，便携版最大的好处就是不用安装，重装系统、更换电脑等烦恼都没有，好处多多，快点不发布吧！

**Comment by aimarxjg** [comment]
同求，一键包最方便了，请大佬抽空做1下啦~谢谢❤️

**Comment by caorushizi** [comment]
已添加，下个版本更新
