### ISSUE TITLE
2.2.2下载不了，退回到2.02就正常

### ISSUE THREAD

**Issue by simplove** [caorushizi/mediago#197]
连接是m3u8的，同一个链接来着的。

**Comment by simplove** [comment]
v2.2.3-beta.0也是下载失败
m3u8是video.twimg.com开头的

**Comment by caorushizi** [comment]
可以发一下视频链接吗

**Comment by simplove** [comment]
https://video.twimg.com/ext_tw_video/1804833772946464769/pu/vid/avc1/720x1280/DMy-_TMbQ6VezqIe.mp4
比如这个，随便一个都不行。

**Comment by caorushizi** [comment]
我试了一下最新版本是可以的
