### ISSUE TITLE
macOS版本启动后不显示界面

### ISSUE THREAD

**Issue by DanielZWX** [caorushizi/mediago#230]
macOS版本启动后不显示界面，只在docker区显示图标

v2.2.0 正常没问题， v2.2.1 - v2.2.3（最新版） 都存在此问题

**Comment by 464917671** [comment]
是的。确实存在。

**Comment by 464917671** [comment]
能不能给个 2.2.0 版本，？？？qq 825888682

**Comment by gatspy** [comment]
v2.2.3 遇到同样问题

**Comment by binglww** [comment]
一样的问题 mac os 11.2.3

**Comment by leveychen** [comment]
> 一样的问题 mac os 15.0

补充一下，3.0 beta 可以正常显示使用。但3.0 beta 没有签名，会默认被丢到废纸篓。

可终端运行`sudo xattr -dr com.apple.quarantine /Applications/mediago.app`
解除限制。

**Comment by ruanjiayou** [comment]
系统
mac os 12.7.4 Intel Core i5  打不开
软件
mediago-setup-x64-2.2.3.dmg
终端运行还是打不开 `sudo xattr -dr com.apple.quarantine /Applications/mediago.app`

**Comment by MisteryLiuCode** [comment]
macos13 mediago-setup-x64-2.2.3.dmg还是打不开

**Comment by caorushizi** [comment]
可以安装 v3.0 版本： https://github.com/caorushizi/mediago/releases/tag/v3.0.0
- 【Intel 芯片】需要安装 release 中的 x64 版本。安装完成后需要在 Mac 的安全设置中打开来自身份不明开发者的 Mac App
- 【Apple 芯片】需要安装 release 中的 arm64 芯片。安装完成后需要在控制台执行 `sudo xattr -dr com.apple.quarantine /Applications/mediago.app` 命令
