### ISSUE TITLE
需要优化批量下载功能

### ISSUE THREAD

**Issue by Heathledger1019** [caorushizi/mediago#244]
最近使用的 2.2.0版本下载动漫番剧（我主要用来下载，地址是自己用F12获取的），原来的批量下载用起来，真的很方便。但是会强制更新成2.2.3，且批量下载功能 发生了变化，用起来用户体验不是很好。

2.2.3用起来不友好的地方：
1、录入任务，不够简洁，比较强制性的限制文件名，不能支持从第4集下载到第8集这样的操作。
2、原来新建任务，只需要 点新建，然后填文件名 和地址就可以，现在强制必须要 选一下  下载 m3u8 还是 b站视频。。。。鼠标需要多点几下。
3、新建任务的按钮，文本提示不明显，考虑修改为：【添加并立马开始下载】、【添加】、【取消】

所以，批量下载功能 希望能够支持以下2种方式，来录入任务（主要建议）

第一种，一个大输入框（直接黏贴）（类似旧版本一样）：

文件名+空格+m3u8地址
文件名+空格+m3u8地址
文件名+空格+m3u8地址

或者 

文件名1
文件名2
文件名3
m3u8地址1
m3u8地址2
m3u8地址3

第二种（输入变量，自动生成文件名）：

剧集名:_____+ 第___集开始 + 第___集结束

（大文本框 黏贴地址）
m3u8地址
m3u8地址
m3u8地址

预期下载结果：
文件名-1.mp4
文件名-2.mp4
文件名-3.mp4

**Comment by caorushizi** [comment]
已修改，下个版本更新
