### ISSUE TITLE
新增下载界面中的微调建议

### ISSUE THREAD

**Issue by fjqingyou** [caorushizi/mediago#273]
新增下载界面中，视频类型添加一个默认选择上次选择的功能吧。实际使用中，并不是每次都不同，大部分情况下多是同环境连续新增下载，有个默认可以少选择一次
同理，在视频名称中的 剧集、电影 的类型方面，大部分情况下也会是相同类型的情况比较多，希望也是默认选择上次选择的类型

**Comment by caorushizi** [comment]
下一个beta版本更新
