### ISSUE TITLE
Windows下开发环境问题

### ISSUE THREAD

**Issue by liesauer** [caorushizi/mediago#362]
不确定是这个项目有意这样要求还是没考虑到这种情况，特发起提问。

开发环境：
Windows + WSL

问题：
在运行`pnpm dev`时，会报各种莫名其妙的报错（取决于node版本、是否使用corepack等因素），其中包括但不局限于：
1. `Cannot find module 'fs/promises'`
2. `This version of pnpm requires at least Node.js vXXX`
3. `This: not found`

经过了一个晚上的折腾，重装Node、重装pnpm，折腾了无数遍终于找到问题所在了。

`pnpm dev`会调用`scripts/dev.ts`，其中会引用到`zx`这个库，而`zx`不知道处于什么考虑，在存在wsl的情况下，会直接调用wsl的node环境，而不是host的node环境，我host系统中node是v18.12.0，wsl中node是v12.22.6。

所以以下代码实际上会在wsl系统中的v12版本的node环境中运行，也就是导致上面所说的一堆莫名其妙的报错的来源。

https://github.com/caorushizi/mediago/blob/9cb57890805556f6814abca3fd28f317a38e5dea/scripts/dev.ts#L8-L12

日志中也是可以验证的，后面的目录格式已经从Windows格式变成Linux格式了
```
开始构建 development ...
当前所在的目录是: O:\Projects\mediago
$ npm run types

> mediago@0.1.0 types /mnt/o/Projects/mediago
> pnpm -F main run types
```

经过查阅资料后，在`scripts/dev.ts`添加以下配置后，一切正常运行了
```
if (process.platform === 'win32') {
    $.prefix = '';
    $.shell = 'pwsh.exe';
}
```

**Comment by liesauer** [comment]
同理，其他脚本只要使用了`zx`，同样存在这个问题。

**Comment by caorushizi** [comment]
感谢指正，有时间可以提个 pr
