### ISSUE TITLE
下载片段较多的m3u8视频时出错

### ISSUE THREAD

**Issue by ScienceZone** [caorushizi/mediago#79]
问题描述：使用2.02版本下载片段较多的m3u8视频时出错，视频有2000多个片段，设置勾选了“下载完成删除分片”，实际显示下载完成后发现大量分片和存在，似乎至少了200个，另外多出T0000到T0002三个几十M的视频，但相对完整视频大小1G多来说还是太小了，这三个视频内容是工具合并成的原视频前面的部分内容。希望解决，谢谢！

**Comment by caorushizi** [comment]
最新版本试下
